Feature/add new habit
ese-varo/growing pull request #4
Opened 2021-03-30 00:36 UTC by GregVaz

## Explain why this change is being made
As an user, I want to add new habits so that I can create one habit

## Explain how this is accomplished

- One habit is created 
- Once the habit is created it redirects to you to the habit details page

## How do you manually test this?
1. Visit the habits page
2. Click the button Create new Habit
3. Fill in the form with the name, description, start date and habit's duration
4. Click button Create Habit
5. It will show you the information of the habit 

#### Screenshots (if any)

2021-03-30 22:07 UTC, LoginALee approved these changes

2021-03-30 22:19 UTC, ese-varo approved these changes
I left some comments, but it actually seems great, well done guys! :rocket:

2021-03-30 22:19 UTC, ese-varo commented on spec/features/create_new_habit_spec.rb
> +    fill_in 'Quantity', with: 30
is it always going to have 30 days as quantity? if not, what do you think about random numbers between a range?

2021-03-30 22:19 UTC, ese-varo commented on spec/features/create_new_habit_spec.rb
> +    fill_in 'Quantity', with: 30
same here

2021-03-30 22:35 UTC, GregVaz commented on spec/features/create_new_habit_spec.rb
> +    fill_in 'Quantity', with: 30
Done, that's a good point, yeah it could be with the range between 21 and 66

2021-03-30 22:35 UTC, LoginALee approved these changes
Cool, Good job guys :heart:

2021-03-30 22:36 UTC, ese-varo approved these changes

2021-03-31 00:20 UTC, OmauryMarmolejo requested changes

2021-03-31 00:20 UTC, OmauryMarmolejo commented on app/controllers/habits_controller.rb
> +    params[:habit][:start_date].to_date + params[:habit][:quantity].to_i.days
What happens if the start_date is not present? Also, What is `quantity`?

2021-03-31 00:20 UTC, OmauryMarmolejo commented on app/controllers/habits_controller.rb
> +    params.require(:habit).permit(:name, :description, :start_date).merge(:end_date => end_date_param)
Please, try to use colon syntax `end_date: ...`

2021-03-31 00:20 UTC, OmauryMarmolejo commented on app/helpers/habits_helper.rb
> +module HabitsHelper
Is this file needed?

2021-03-31 00:20 UTC, OmauryMarmolejo commented on app/views/habits/index.html.haml
> +        %h5.modal-title#staticBackdropLabel>Create a new habit
Is this line correct?

2021-03-31 00:20 UTC, OmauryMarmolejo commented on app/views/layouts/application.html.erb
> +    <div class='container'>
You include this div for every place you use the application layout. There are no exceptions?

2021-03-31 17:20 UTC, jvargas98 commented on app/views/layouts/application.html.erb
> +    <div class='container'>
yes, we believe that there are no exceptions and that it cannot affect future features. 🤔

2021-03-31 17:48 UTC, jvargas98 commented on app/views/habits/index.html.haml
> +        %h5.modal-title#staticBackdropLabel>Create a new habit
already changed, thanks

2021-03-31 17:49 UTC, GregVaz commented on app/controllers/habits_controller.rb
> +    params[:habit][:start_date].to_date + params[:habit][:quantity].to_i.days
We already solved this, we change the name of quantity by habit_duration, it is more understandable
And raise an exception when the attribute in params does not exist

2021-03-31 17:49 UTC, GregVaz commented on app/controllers/habits_controller.rb
> +    params.require(:habit).permit(:name, :description, :start_date).merge(:end_date => end_date_param)
Sure, thanks :D

2021-03-31 17:49 UTC, jvargas98 commented on app/helpers/habits_helper.rb
> +module HabitsHelper
we have already removed it

2021-03-31 17:55 UTC, ese-varo approved these changes

2021-03-31 18:11 UTC, LoginALee approved these changes

2021-03-31 19:33 UTC, OmauryMarmolejo approved these changes

2021-03-31 23:33 UTC, closed without merging